window.SITE_CONFIG = {
  siteName: "青森の実家係",
  operatorTradeName: "空き家レスキュー",
  operatorName: "名久井 海里",
  operatorAddress: "〒030-0862 青森県青森市古川1丁目12-2 ポレスター古川プレミアムレジデンス1503",
  phone: "090-1064-3213",
  phoneHref: "tel:09010643213",
  email: "aomori.akiya.rescue@gmail.com",
  emailHref: "mailto:aomori.akiya.rescue@gmail.com",
  businessHours: "平日9:00〜18:00（土日祝休業）",
  responseTime: "原則1営業日以内",
  serviceStatus: "inquiry",
  normalArea: "青森市内（事業拠点から片道20km以内）",
  surchargeArea: "青森市内の片道20km超〜35km以内：1回につき1,100円加算",
  outOfArea: "片道35km超、冬季通行止め地域、安全に訪問できない地域は原則対象外",
  surchargeNote: "駐車料金・有料道路代は実費。通常を超える積雪等は事前見積りです。",
  membershipPrice: "980円／月（税込）",
  memberVisitPrice: "4,980円／回（税込）",
  nonMemberVisitPrice: "7,700円／回（税込）",
  membershipPaymentUrl: "",
  memberVisitPaymentUrl: "",
  nonMemberVisitPaymentUrl: "",
  inquiryUrl: "mailto:aomori.akiya.rescue@gmail.com?subject=青森の実家係へのお問い合わせ",
  cancellationUrl: "mailto:aomori.akiya.rescue@gmail.com?subject=月額会員の解約手続",
  launchDate: "2026年8月3日",
  currentUrl: "https://aomori-akiya-rescue.pages.dev",
  paymentMethod: "クレジットカード（Stripeを予定）"
};
