'use strict';
const C={build:'2026-08-15-supabase-v2',api:'https://fpgtwgtoqtokpitzlbie.supabase.co/functions/v1/event-platform-api',match:60};
const T={event:'イベント',venue:'会場・場所',promotion:'広報・集客',exhibitor:'出店・販売',performer:'出演・コンテンツ',staff:'運営協力'},N={venue:'会場・場所',promotion:'広報・集客',exhibitor:'出店・販売',performer:'出演・コンテンツ',staff:'運営協力'};
const $=x=>document.getElementById(x),txt=x=>String(x??'').trim(),norm=x=>txt(x).normalize('NFKC').toLowerCase().replace(/\s+/g,' '),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let R={},D={listings:[],incoming:[],outgoing:[],notifications:[],relatedListings:[]},postType='event',online=false,boot=false;
const K=x=>'event_platform_'+x,read=(x,d)=>{try{let v=localStorage.getItem(K(x));return v===null?d:JSON.parse(v)}catch{return d}},write=(x,v)=>localStorage.setItem(K(x),JSON.stringify(v));
function secret(){let a=crypto.getRandomValues(new Uint8Array(32));return[...a].map(b=>b.toString(16).padStart(2,'0')).join('')}
function identity(){let v=read('identity',null);if(!v||!/^[0-9a-f-]{36}$/i.test(v.ownerId||'')||txt(v.ownerKey).length<32){v={ownerId:crypto.randomUUID(),ownerKey:secret(),createdAt:new Date().toISOString()};write('identity',v)}return v}
const headers=()=>({'x-owner-id':identity().ownerId,'x-owner-key':identity().ownerKey});
function toast(s){let e=$('toast');e.textContent=s;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),4200)}
function safeUrl(v){try{let u=new URL(txt(v));return u.protocol==='https:'?u.href:''}catch{return''}}
async function api(action,opt={}){let h={'Content-Type':'application/json'};if(opt.auth)Object.assign(h,headers());let r=await fetch(C.api+'?action='+encodeURIComponent(action),{method:opt.method||'GET',headers:h,body:opt.body===undefined?undefined:JSON.stringify(opt.body),cache:'no-store'}),d=await r.json().catch(()=>({ok:false,error:'INVALID_RESPONSE'}));if(!r.ok||d.ok===false){let e=new Error(d.error||'HTTP_'+r.status);e.data=d;throw e}return d}
function conn(ok,n=''){online=ok;$('storageStatus').className='status '+(ok?'online':'bad');$('storageStatus').textContent=ok?'本番API接続':'キャッシュ閲覧';$('storageNote').textContent=n;document.querySelectorAll('[data-write-action]').forEach(b=>b.disabled=!ok)}
const mapL=r=>({id:r.id,type:r.type,title:r.title,area:r.area,category:r.category,description:r.description,dateStart:r.date_start||'',dateEnd:r.date_end||'',needs:r.needs||[],availableFrom:r.available_from||'',availableTo:r.available_to||'',capacity:+(r.capacity||0),priceGuide:r.price_guide||'',channels:r.channels||'',tags:r.tags||[],contactUrl:r.contact_url||'',status:r.status||'published',interestCount:+(r.interest_count||0),createdAt:r.created_at||'',updatedAt:r.updated_at||'',moderationWarnings:r.moderation_warnings||[],autoStatusReason:r.auto_status_reason||''});
const mapQ=r=>({id:r.id,fromOwnerId:r.from_owner_id,toOwnerId:r.to_owner_id,sourceListingId:r.source_listing_id,targetListingId:r.target_listing_id,message:r.message||'',score:+(r.score||0),status:r.status,createdAt:r.created_at});
async function bootstrap(){try{await api('bootstrap',{method:'POST',auth:true,body:{}});return boot=true}catch(e){console.error(e);return boot=false}}
async function publicLoad(){try{let d=await api('public_listings');R=Object.fromEntries((d.listings||[]).map(x=>{let r=mapL(x);return[r.id,r]}));write('cache',R);conn(true,'（Supabase共有DB）');renderAll();return true}catch(e){R=read('cache',{});conn(false,'（API障害中。投稿は停止）');renderAll();return false}}
async function dashLoad(){if(!online||!boot)return;try{let d=await api('dashboard',{auth:true});D={listings:(d.listings||[]).map(mapL),incoming:(d.incoming||[]).map(mapQ),outgoing:(d.outgoing||[]).map(mapQ),notifications:d.notifications||[],relatedListings:d.relatedListings||[]};write('dash',D);renderDashboard();notify()}catch(e){D=read('dash',D);renderDashboard()}}
async function refresh(){let ok=await publicLoad();if(ok&&!boot)await bootstrap();if(ok&&boot)await dashLoad()}
function chip(c,s){return`<span class="chip ${esc(c||'')}">${esc(s)}</span>`}
const needs=r=>(r.needs||[]).map(x=>`<span class="chip need">${esc(N[x]||x)}</span>`).join('');
const status=r=>r.status==='review_required'?chip('pending','要修正'):r.status==='auto_hidden'?chip('hidden','自動停止'):r.status==='expired'?chip('expired','期限切れ'):r.status==='stale'?chip('expired','更新待ち'):'';
const pubs=()=>Object.values(R).filter(r=>r.status==='published'),favs=()=>read('fav',[]),setFav=a=>write('fav',[...new Set(a)]),own=()=>new Map(D.listings.map(r=>[r.id,r]));
function score(e,r){if(!e||e.type!=='event'||r.type==='event'||!(e.needs||[]).includes(r.type)||e.status!=='published'||r.status!=='published')return 0;let s=10,a=norm(e.area),b=norm(r.area);if(a===b)s+=30;else if(a.includes(b)||b.includes(a))s+=20;if(e.category===r.category)s+=18;let et=new Set(e.tags||[]);s+=Math.min(20,(r.tags||[]).filter(x=>et.has(x)).length*5);if(r.availableFrom&&e.dateEnd&&r.availableFrom>e.dateEnd)return 0;if(r.availableTo&&e.dateStart&&r.availableTo<e.dateStart)return 0;if(r.availableFrom||r.availableTo)s+=12;if(r.type==='venue'&&r.capacity)s+=5;return Math.min(100,s)}
function recs(e){return pubs().filter(r=>r.type!=='event').map(r=>({r,s:score(e,r)})).filter(x=>x.s).sort((a,b)=>b.s-a.s).slice(0,15)}
function card(r,s=null){let f=favs().includes(r.id);return`<article class="card"><div class="meta">${chip(r.type,T[r.type]||r.type)}${chip('',r.area)}${chip('',r.category)}${needs(r)}${status(r)}</div><h3>${esc(r.title)}</h3>${r.type==='event'?`<div class="muted">${esc(r.dateStart)} 〜 ${esc(r.dateEnd)}</div>`:''}<p>${esc((r.description||'').slice(0,145))}${(r.description||'').length>145?'…':''}</p>${s!==null?`<div class="score">一致度 ${s}点</div>`:''}<div class="card-footer"><button class="btn primary small" data-detail="${r.id}">詳細</button><button class="btn ghost small" data-fav="${r.id}">${f?'★':'☆'}</button></div></article>`}
function bind(root=document){root.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail));root.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>toggleFav(b.dataset.fav));root.querySelectorAll('[data-interest]').forEach(b=>b.onclick=()=>interest(b.dataset.interest,b.dataset.source||''));root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>del(b.dataset.delete));root.querySelectorAll('[data-renew]').forEach(b=>b.onclick=()=>renew(b.dataset.renew));root.querySelectorAll('[data-request-action]').forEach(b=>b.onclick=()=>answer(b.dataset.requestAction,b.dataset.id))}
function filter(){let q=norm($('q').value),t=$('typeFilter').value,a=norm($('areaFilter').value),n=$('needFilter').value,x=pubs().filter(r=>(!q||norm([r.title,r.area,r.category,r.description,(r.tags||[]).join(' ')].join(' ')).includes(q))&&(!t||r.type===t)&&(!a||norm(r.area).includes(a))&&(!n||(r.needs||[]).includes(n)||r.type===n));if($('sort').value==='date')x.sort((a,b)=>String(a.dateStart||'9999').localeCompare(String(b.dateStart||'9999')));else if($('sort').value==='popular')x.sort((a,b)=>b.interestCount-a.interestCount);else x.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));return x}
function renderBrowse(){let a=filter();$('listingGrid').innerHTML=a.length?a.map(r=>card(r)).join(''):'<div class="empty">条件に合う公開掲載はありません。</div>';bind($('listingGrid'));let p=pubs();$('kEvent').textContent=p.filter(x=>x.type==='event').length;$('kResource').textContent=p.filter(x=>x.type!=='event').length;$('kMatch').textContent=p.filter(x=>x.type==='event').reduce((n,e)=>n+recs(e).filter(x=>x.s>=C.match).length,0);$('kRequest').textContent=D.incoming.length+D.outgoing.length}
function route(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));if(id==='dashboard')renderDashboard();if(id==='favorites')renderFav();history.replaceState(null,'','#'+id);scrollTo({top:0,behavior:'smooth'})}
function setType(t){postType=t;$('postType').value=t;document.querySelectorAll('[data-post-type]').forEach(b=>b.classList.toggle('active',b.dataset.postType===t));document.querySelectorAll('.event-only').forEach(e=>e.style.display=t==='event'?'':'none');document.querySelectorAll('.resource-only').forEach(e=>e.style.display=t!=='event'?'':'none');document.querySelectorAll('.venue-only').forEach(e=>e.style.display=t==='venue'?'':'none');document.querySelectorAll('.promotion-only').forEach(e=>e.style.display=t==='promotion'?'':'none')}
function detail(id){let r=R[id]||D.listings.find(x=>x.id===id);if(!r)return;$('modalType').textContent=T[r.type]||r.type;$('modalType').className='chip '+r.type;$('modalTitle').textContent=r.title;let extra='';if(r.type==='venue')extra+=`<p><b>収容人数:</b> ${esc(r.capacity||'未設定')}</p>`;if(r.channels)extra+=`<p><b>対応媒体:</b> ${esc(r.channels)}</p>`;if(r.priceGuide)extra+=`<p><b>料金目安:</b> ${esc(r.priceGuide)}</p>`;let m='';if(r.type==='event'){let z=recs(r);m=`<div class="divider"></div><h3>自動マッチ候補</h3><div class="match-columns">${Object.keys(N).filter(n=>(r.needs||[]).includes(n)).map(n=>`<div><div class="subhead">${N[n]}</div>${z.filter(x=>x.r.type===n).map(x=>card(x.r,x.s)).join('')||'<div class="empty">候補なし</div>'}</div>`).join('')}</div>`}let self=own().has(r.id),u=safeUrl(r.contactUrl);$('modalBody').innerHTML=`<div class="meta">${chip('',r.area)}${chip('',r.category)}${needs(r)}</div>${r.type==='event'?`<p><b>開催:</b> ${esc(r.dateStart)} 〜 ${esc(r.dateEnd)}</p>`:''}<div class="detail-copy">${esc(r.description)}</div>${extra}<div class="actions">${u?`<a class="btn primary" target="_blank" rel="noopener noreferrer" href="${esc(u)}">公開問い合わせ先</a>`:''}${!self?`<button class="btn ok" data-write-action data-interest="${r.id}">マッチ希望</button><button class="btn ghost" data-write-action id="reportBtn">通報</button>`:''}<button class="btn ghost" id="shareBtn">共有</button></div>${m}`;$('modal').classList.add('open');bind($('modalBody'));if($('reportBtn'))$('reportBtn').onclick=()=>report(id);$('shareBtn').onclick=()=>share(id);document.querySelectorAll('[data-write-action]').forEach(b=>b.disabled=!online)}
function closeModal(){$('modal').classList.remove('open')}
function toggleFav(id){let a=favs(),i=a.indexOf(id);i>=0?a.splice(i,1):a.push(id);setFav(a);renderAll()}
async function ready(){if(!online){toast('現在は書込みできません。');return false}if(!boot&&!(await bootstrap())){toast('管理鍵の初期化に失敗しました。');return false}return true}
async function report(id){if(!(await ready()))return;let reason=prompt('問題の内容を入力してください。','内容確認依頼');if(reason===null||!txt(reason))return;try{await api('report',{method:'POST',auth:true,body:{listingId:id,reason:txt(reason)}});toast('通報を受け付けました。');await refresh();closeModal()}catch(e){toast(errmsg(e))}}
async function interest(target,source=''){if(!(await ready()))return;let mine=D.listings.filter(r=>r.status==='published'),s=source?mine.find(r=>r.id===source):null;if(!s&&mine.length===1)s=mine[0];if(!s&&mine.length>1){let n=+prompt(mine.map((r,i)=>`${i+1}: ${r.title}`).join('\n'));if(n>0&&n<=mine.length)s=mine[n-1]}if(!s){toast('先に自分の掲載を公開してください。');return}let msg=prompt('相手へ伝える一言','条件が合えば詳細を相談したいです。');if(msg===null)return;try{await api('create_interest',{method:'POST',auth:true,body:{sourceListingId:s.id,targetListingId:target,message:txt(msg)}});toast('マッチ希望を送信しました。');await refresh();closeModal()}catch(e){toast(errmsg(e))}}
function rel(id){let r=D.relatedListings.find(x=>x.id===id)||D.listings.find(x=>x.id===id)||R[id];return r?.title||'削除済み'}
function reqCard(r,incoming){return`<article class="request-card"><div class="request-head"><b>${esc(rel(r.sourceListingId))} → ${esc(rel(r.targetListingId))}</b>${chip(r.status,{pending:'回答待ち',accepted:'成立',declined:'辞退'}[r.status]||r.status)}</div><p>${esc(r.message)}</p>${r.score?`<div class="score">一致度 ${r.score}点</div>`:''}${incoming&&r.status==='pending'?`<div class="card-footer"><button class="btn ok small" data-write-action data-request-action="accept" data-id="${r.id}">承認</button><button class="btn ghost small" data-write-action data-request-action="decline" data-id="${r.id}">辞退</button></div>`:''}</article>`}
async function answer(a,id){if(!(await ready()))return;try{await api('request_action',{method:'POST',auth:true,body:{id,decision:a==='accept'?'accepted':'declined'}});toast(a==='accept'?'承認しました。':'辞退しました。');await refresh()}catch(e){toast(errmsg(e))}}
function opportunities(){let out=[];for(let r of D.listings.filter(x=>x.status==='published')){if(r.type==='event')recs(r).forEach(x=>out.push({s:r,t:x.r,n:x.s}));else pubs().filter(e=>e.type==='event'&&(e.needs||[]).includes(r.type)).forEach(e=>{let n=score(e,r);if(n)out.push({s:r,t:e,n})})}return out.sort((a,b)=>b.n-a.n).slice(0,30)}
function renderDashboard(){let m=D.listings;$('mineGrid').innerHTML=m.length?m.map(r=>`<article class="card"><div class="meta">${chip(r.type,T[r.type])}${status(r)}</div><h3>${esc(r.title)}</h3><p>${esc(r.area)} / ${esc(r.category)}</p>${r.moderationWarnings?.length?`<div class="notice-warn">${r.moderationWarnings.map(esc).join('<br>')}</div>`:''}${r.autoStatusReason?`<p class="muted">${esc(r.autoStatusReason)}</p>`:''}<div class="card-footer"><button class="btn primary small" data-write-action data-edit="${r.id}">編集</button>${r.status==='stale'?`<button class="btn ok small" data-write-action data-renew="${r.id}">更新</button>`:''}<button class="btn danger small" data-write-action data-delete="${r.id}">削除</button></div></article>`).join(''):'<div class="empty">掲載はありません。</div>';$('incomingList').innerHTML=D.incoming.map(r=>reqCard(r,true)).join('')||'<div class="empty">受信なし</div>';$('outgoingList').innerHTML=D.outgoing.map(r=>reqCard(r,false)).join('')||'<div class="empty">送信なし</div>';let o=opportunities();$('opportunityGrid').innerHTML=o.map(x=>`<article class="card"><div class="score">一致度 ${x.n}点</div><h3>${esc(x.s.title)}</h3><p>候補：${esc(x.t.title)}</p><div class="card-footer"><button class="btn primary small" data-detail="${x.t.id}">見る</button><button class="btn ok small" data-write-action data-interest="${x.t.id}" data-source="${x.s.id}">マッチ希望</button></div></article>`).join('')||'<div class="empty">候補なし</div>';$('notificationList').innerHTML=D.notifications.map(n=>`<article class="request-card"><div class="request-head"><b>${esc(n.title)}</b>${chip(n.status,n.status==='unread'?'未読':'既読')}</div><p>${esc(n.message||'')}</p></article>`).join('')||'<div class="empty">通知なし</div>';$('identityBox').innerHTML=`運営ID: <b>${identity().ownerId}</b> ／ 未読通知 <b>${D.notifications.filter(n=>n.status==='unread').length}</b>件`;bind($('dashboard'));renderSystem();document.querySelectorAll('[data-write-action]').forEach(b=>b.disabled=!online)}
function renderFav(){let a=favs().map(id=>R[id]).filter(Boolean);$('favGrid').innerHTML=a.map(r=>card(r)).join('')||'<div class="empty">お気に入りはありません。</div>';bind($('favGrid'))}
function renderSystem(){$('systemBox').innerHTML=`<h3>本番自動運転</h3><p>Frontend: <b>${C.build}</b></p><p>API: <b>${online?'接続済み':'障害・閲覧キャッシュのみ'}</b></p><p>共有DB: <b>Supabase PostgreSQL</b></p><p>サーバ側自動審査／期限切れ／180日未更新／独立通報3件／高一致候補／マッチ通知を自動処理。</p><div class="notice-warn">料金・手数料・決済は元トークの確定仕様を取得できていないため有効化していません。</div>`}
function renderAll(){renderBrowse();renderDashboard();renderFav()}
function payload(){return{type:postType,title:txt($('title').value),area:txt($('area').value),category:$('category').value,description:txt($('description').value),dateStart:$('dateStart').value,dateEnd:$('dateEnd').value,needs:[...document.querySelectorAll('.need:checked')].map(x=>x.value),availableFrom:$('availableFrom').value,availableTo:$('availableTo').value,capacity:+($('capacity').value||0),priceGuide:txt($('priceGuide').value),channels:txt($('channels').value),tags:txt($('tags').value).split(/[,、]/).map(norm).filter(Boolean),contactUrl:txt($('contactUrl').value)}}
async function save(e){e.preventDefault();if(!(await ready()))return;if(!$('terms').checked){toast('掲載条件への同意が必要です。');return}let p=payload(),id=txt($('editId').value);try{let d=await api('save_listing',{method:'POST',auth:true,body:{...p,id:id||undefined}});toast(d.status==='published'?'公開しました。':'要修正として保存しました。');reset();await refresh();route('dashboard')}catch(e){let z=e.data||{};$('validationBox').innerHTML=`<div class="notice-bad">${[...(z.errors||[]),...(z.warnings||[]),errmsg(e)].map(esc).join('<br>')}</div>`}}
function reset(){$('postForm').reset();$('editId').value='';$('submitBtn').textContent='自動審査して掲載';$('postHeading').textContent='掲載する';$('validationBox').innerHTML='';setType(postType)}
function edit(id){let r=D.listings.find(x=>x.id===id);if(!r)return;route('post');setType(r.type);$('editId').value=id;$('postHeading').textContent='掲載を編集';$('submitBtn').textContent='自動審査して更新';for(let [a,b] of [['title','title'],['area','area'],['category','category'],['description','description'],['dateStart','dateStart'],['dateEnd','dateEnd'],['availableFrom','availableFrom'],['availableTo','availableTo'],['capacity','capacity'],['priceGuide','priceGuide'],['channels','channels'],['contactUrl','contactUrl']])$(a).value=r[b]||'';$('tags').value=(r.tags||[]).join(', ');document.querySelectorAll('.need').forEach(c=>c.checked=(r.needs||[]).includes(c.value));$('terms').checked=true}
async function del(id){if(!(await ready())||!confirm('この掲載を削除しますか？'))return;try{await api('delete_listing',{method:'POST',auth:true,body:{id}});toast('削除しました。');await refresh()}catch(e){toast(errmsg(e))}}
async function renew(id){if(!(await ready()))return;try{await api('renew_listing',{method:'POST',auth:true,body:{id}});toast('更新しました。');await refresh()}catch(e){toast(errmsg(e))}}
async function share(id){let u=location.origin+location.pathname+'#listing='+id;try{navigator.share?await navigator.share({title:R[id]?.title,url:u}):(await navigator.clipboard.writeText(u),toast('URLをコピーしました。'))}catch{}}
function notify(){let seen=read('seen',{}),n={...seen};D.notifications.filter(x=>x.status==='unread').forEach(x=>{if(seen[x.id])return;n[x.id]=Date.now();if('Notification'in window&&Notification.permission==='granted')try{new Notification(x.title,{body:x.message,tag:x.id})}catch{};toast(x.title)});write('seen',n)}
async function markRead(){if(!(await ready()))return;try{await api('mark_notifications_read',{method:'POST',auth:true,body:{}});await dashLoad()}catch(e){toast(errmsg(e))}}
function backup(){let b=new Blob([JSON.stringify({version:C.build,identity:identity(),favorites:favs()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='event-platform-owner-backup.json';a.click()}
async function restore(f){try{let d=JSON.parse(await f.text());if(!d.identity||!/^[0-9a-f-]{36}$/i.test(d.identity.ownerId)||txt(d.identity.ownerKey).length<32)throw 0;write('identity',d.identity);if(Array.isArray(d.favorites))setFav(d.favorites);boot=false;if(!(await bootstrap()))throw 0;toast('管理鍵を復元しました。');await refresh()}catch{toast('バックアップを復元できませんでした。')}}
function errmsg(e){let c=e?.data?.error||e?.message||'UNKNOWN';return({AUTH_FAILED:'管理鍵が一致しません。',MODERATION_REJECTED:'自動審査で掲載できません。',DUPLICATE_REQUEST:'同じ相手への有効な希望があります。',FORBIDDEN:'操作権限がありません。',SELF_REPORT:'自分の掲載は通報できません。',RATE_LIMIT:'短時間の操作上限です。'}[c]||`処理失敗（${c}）`)}
function wire(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=e=>{e.preventDefault();route(b.dataset.nav)});document.querySelectorAll('[data-post-type]').forEach(b=>b.onclick=()=>setType(b.dataset.postType));document.querySelectorAll('[data-dash]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-dash]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.dash-panel').forEach(x=>x.classList.toggle('active',x.id===b.dataset.dash))});['q','areaFilter'].forEach(x=>$(x).oninput=renderBrowse);['typeFilter','needFilter','sort'].forEach(x=>$(x).onchange=renderBrowse);$('postForm').onsubmit=save;$('resetBtn').onclick=reset;$('modalClose').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};$('healthBtn').onclick=async()=>{try{let d=await api('health');conn(true,'（Supabase共有DB）');toast('自己診断正常 / '+d.build)}catch{conn(false,'（API障害中）')}};$('notifyBtn').onclick=async()=>{if(!('Notification'in window)){toast('このブラウザは通知非対応です。');return}toast(await Notification.requestPermission()==='granted'?'通知を有効化しました。':'通知は有効になりませんでした。')};$('markReadBtn').onclick=markRead;$('exportBtn').onclick=backup;$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=()=>$('importFile').files?.[0]&&restore($('importFile').files[0]);setType('event')}
window.addEventListener('DOMContentLoaded',async()=>{wire();identity();await publicLoad();if(online){boot=await bootstrap();if(boot)await dashLoad()}let h=location.hash.slice(1);if(h.startsWith('listing=')&&R[h.slice(8)])detail(h.slice(8));else if(['browse','post','dashboard','favorites'].includes(h))route(h);setInterval(refresh,60000)});