'use strict';
const C={build:'2026-08-26-zero-license-ui-v1',api:'https://fpgtwgtoqtokpitzlbie.supabase.co/functions/v1/event-platform-api',match:60};
const T={event:'イベント',venue:'会場・施設情報',promotion:'広報・集客サービス',exhibitor:'出店・販売事業者',performer:'出演・コンテンツ事業者',contractor:'運営業務サービス（業務委託）'};
const N={venue:'会場・施設',promotion:'広報・集客',exhibitor:'出店・販売',performer:'出演・コンテンツ',contractor:'運営業務サービス'};
const $=id=>document.getElementById(id),txt=v=>String(v??'').trim(),norm=v=>txt(v).normalize('NFKC').toLowerCase().replace(/\s+/g,' '),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const K=x=>'event_platform_'+x,read=(x,d)=>{try{const v=localStorage.getItem(K(x));return v===null?d:JSON.parse(v)}catch{return d}},write=(x,v)=>localStorage.setItem(K(x),JSON.stringify(v));
let R={},D={listings:[],notifications:[]},postType='event',online=false,boot=false;
function secret(){const a=crypto.getRandomValues(new Uint8Array(32));return[...a].map(b=>b.toString(16).padStart(2,'0')).join('')}
function identity(){let v=read('identity',null);if(!v||!/^[0-9a-f-]{36}$/i.test(v.ownerId||'')||txt(v.ownerKey).length<32){v={ownerId:crypto.randomUUID(),ownerKey:secret(),createdAt:new Date().toISOString()};write('identity',v)}return v}
const headers=()=>({'x-owner-id':identity().ownerId,'x-owner-key':identity().ownerKey});
function toast(s){const e=$('toast');if(!e)return;e.textContent=s;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),4200)}
function safeUrl(v){try{const u=new URL(txt(v));return u.protocol==='https:'?u.href:''}catch{return''}}
async function api(action,opt={}){const h={'Content-Type':'application/json'};if(opt.auth)Object.assign(h,headers());const r=await fetch(C.api+'?action='+encodeURIComponent(action),{method:opt.method||'GET',headers:h,body:opt.body===undefined?undefined:JSON.stringify(opt.body),cache:'no-store'});const d=await r.json().catch(()=>({ok:false,error:'INVALID_RESPONSE'}));if(!r.ok||d.ok===false){const e=new Error(d.error||'HTTP_'+r.status);e.data=d;throw e}return d}
function conn(ok,n=''){online=ok;$('storageStatus').className='status '+(ok?'online':'bad');$('storageStatus').textContent=ok?'API接続':'キャッシュ閲覧';$('storageNote').textContent=n;document.querySelectorAll('[data-write-action]').forEach(b=>b.disabled=!ok)}
const mapL=r=>({id:r.id,type:r.type,title:r.title,area:r.area,category:r.category,description:r.description,dateStart:r.date_start||'',dateEnd:r.date_end||'',needs:r.needs||[],availableFrom:r.available_from||'',availableTo:r.available_to||'',capacity:+(r.capacity||0),priceGuide:r.price_guide||'',channels:r.channels||'',tags:r.tags||[],contactUrl:r.contact_url||'',status:r.status||'published',createdAt:r.created_at||'',updatedAt:r.updated_at||'',moderationWarnings:r.moderation_warnings||[],autoStatusReason:r.auto_status_reason||'',venueInfoOnly:!!r.venue_info_only,contractorBusinessOnly:!!r.contractor_business_only,legalScopeVersion:r.legal_scope_version||''});
async function bootstrap(){try{await api('bootstrap',{method:'POST',auth:true,body:{}});boot=true;return true}catch(e){console.error(e);boot=false;return false}}
async function publicLoad(){try{const d=await api('public_listings');R=Object.fromEntries((d.listings||[]).map(x=>{const r=mapL(x);return[r.id,r]}));write('cache',R);conn(true,'（共有DB・開発プレビュー）');renderAll();return true}catch(e){console.error(e);R=read('cache',{});conn(false,'（API障害中。投稿は停止）');renderAll();return false}}
async function dashLoad(){if(!online||!boot)return;try{const d=await api('dashboard',{auth:true});D={listings:(d.listings||[]).map(mapL),notifications:d.notifications||[]};write('dash',D);renderDashboard()}catch(e){console.error(e);D=read('dash',D);renderDashboard()}}
async function refresh(){const ok=await publicLoad();if(ok&&!boot)await bootstrap();if(ok&&boot)await dashLoad()}
const pubs=()=>Object.values(R).filter(r=>r.status==='published');
const own=()=>new Map(D.listings.map(r=>[r.id,r]));
const favs=()=>read('fav',[]),setFav=a=>write('fav',[...new Set(a)]);
function chip(c,s){return`<span class="chip ${esc(c||'')}">${esc(s)}</span>`}
const needs=r=>(r.needs||[]).map(x=>`<span class="chip need">${esc(N[x]||x)}</span>`).join('');
const status=r=>r.status==='review_required'?chip('pending','確認待ち'):r.status==='auto_hidden'?chip('hidden','自動停止'):r.status==='expired'?chip('expired','期限切れ'):r.status==='stale'?chip('expired','更新待ち'):'';
function scoreDetail(e,r){if(!e||e.type!=='event'||!r||r.type==='event'||!(e.needs||[]).includes(r.type)||e.status!=='published'||r.status!=='published')return{score:0,reasons:[]};let s=10,reasons=['対象種別 +10'];const ea=norm(e.area),ra=norm(r.area);if(ea===ra){s+=30;reasons.push('地域一致 +30')}else if(ea&&ra&&(ea.includes(ra)||ra.includes(ea))){s+=20;reasons.push('地域部分一致 +20')}if(e.category===r.category){s+=18;reasons.push('カテゴリ一致 +18')}const et=new Set(e.tags||[]),shared=(r.tags||[]).filter(x=>et.has(x));if(shared.length){const p=Math.min(20,shared.length*5);s+=p;reasons.push(`共通タグ ${shared.length}件 +${p}`)}if(r.availableFrom&&e.dateEnd&&r.availableFrom>e.dateEnd)return{score:0,reasons:['対応期間が開催日と重ならない']};if(r.availableTo&&e.dateStart&&r.availableTo<e.dateStart)return{score:0,reasons:['対応期間が開催日と重ならない']};if(r.availableFrom||r.availableTo){s+=12;reasons.push('対応期間確認可 +12')}if(r.type==='venue'&&r.capacity>0){s+=5;reasons.push('収容人数情報あり +5')}return{score:Math.min(100,s),reasons}}
function recommendations(e){return pubs().filter(r=>r.type!=='event').map(r=>({r,...scoreDetail(e,r)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||String(b.r.createdAt).localeCompare(String(a.r.createdAt)))}
function reverseRecommendations(resource){return pubs().filter(e=>e.type==='event').map(e=>({r:e,...scoreDetail(e,resource)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||String(b.r.createdAt).localeCompare(String(a.r.createdAt)))}
function card(r,m=null){const f=favs().includes(r.id);return`<article class="card"><div class="meta">${chip(r.type,T[r.type]||r.type)}${chip('',r.area)}${chip('',r.category)}${needs(r)}${status(r)}</div><h3>${esc(r.title)}</h3>${r.type==='event'?`<div class="muted">${esc(r.dateStart)} 〜 ${esc(r.dateEnd)}</div>`:''}<p>${esc((r.description||'').slice(0,150))}${(r.description||'').length>150?'…':''}</p>${m?`<div class="score-box"><strong>一致度 ${m.score}点</strong><span>${esc(m.reasons.join(' / '))}</span></div>`:''}<div class="card-footer"><button class="btn primary small" data-detail="${r.id}">詳細</button><button class="btn ghost small" data-fav="${r.id}" aria-label="お気に入り">${f?'★':'☆'}</button></div></article>`}
function bind(root=document){root.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail));root.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>toggleFav(b.dataset.fav));root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>del(b.dataset.delete));root.querySelectorAll('[data-renew]').forEach(b=>b.onclick=()=>renew(b.dataset.renew))}
function filtered(){const q=norm($('q').value),t=$('typeFilter').value,a=norm($('areaFilter').value),n=$('needFilter').value;const x=pubs().filter(r=>(!q||norm([r.title,r.area,r.category,r.description,(r.tags||[]).join(' ')].join(' ')).includes(q))&&(!t||r.type===t)&&(!a||norm(r.area).includes(a))&&(!n||(r.needs||[]).includes(n)||r.type===n));if($('sort').value==='date')x.sort((a,b)=>String(a.dateStart||'9999').localeCompare(String(b.dateStart||'9999')));else x.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));return x}
function renderBrowse(){const a=filtered();$('listingGrid').innerHTML=a.length?a.map(r=>card(r)).join(''):'<div class="empty">条件に合う公開情報はありません。</div>';bind($('listingGrid'));const p=pubs();$('kEvent').textContent=p.filter(x=>x.type==='event').length;$('kResource').textContent=p.filter(x=>x.type!=='event').length;$('kMatch').textContent=p.filter(x=>x.type==='event').reduce((n,e)=>n+recommendations(e).filter(x=>x.score>=C.match).length,0);$('kTotal').textContent=p.length}
function route(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));if(id==='dashboard')renderDashboard();if(id==='favorites')renderFav();history.replaceState(null,'','#'+id);scrollTo({top:0,behavior:'smooth'})}
function setType(t){postType=t;$('postType').value=t;document.querySelectorAll('[data-post-type]').forEach(b=>b.classList.toggle('active',b.dataset.postType===t));document.querySelectorAll('.event-only').forEach(e=>e.style.display=t==='event'?'':'none');document.querySelectorAll('.resource-only').forEach(e=>e.style.display=t!=='event'?'':'none');document.querySelectorAll('.venue-only').forEach(e=>e.style.display=t==='venue'?'':'none');document.querySelectorAll('.promotion-only').forEach(e=>e.style.display=t==='promotion'?'':'none');document.querySelectorAll('.contractor-only').forEach(e=>e.style.display=t==='contractor'?'':'none')}
function detail(id){const r=R[id]||D.listings.find(x=>x.id===id);if(!r)return;$('modalType').textContent=T[r.type]||r.type;$('modalType').className='chip '+r.type;$('modalTitle').textContent=r.title;let extra='';if(r.type==='venue')extra+=`<div class="scope-proof"><strong>会場情報のみ</strong><p>当サイトは予約・内見調整・条件交渉・契約・代金受領に関与しません。</p></div><p><b>収容人数:</b> ${esc(r.capacity||'未設定')}</p>`;if(r.type==='contractor')extra+=`<div class="scope-proof"><strong>業務委託サービスのみ</strong><p>雇用求人・求職・職業紹介・労働者派遣には使用できません。</p></div>`;if(r.channels)extra+=`<p><b>対応媒体:</b> ${esc(r.channels)}</p>`;if(r.priceGuide)extra+=`<p><b>料金目安:</b> ${esc(r.priceGuide)}</p>`;let rec='';if(r.type==='event'){const z=recommendations(r).slice(0,12);rec=`<div class="divider"></div><h3>客観条件による候補</h3><p class="muted">表示根拠を公開しています。検索一覧では他の公開情報もすべて確認できます。</p><div class="grid compact-grid">${z.map(x=>card(x.r,x)).join('')||'<div class="empty">候補なし</div>'}</div>`}const self=own().has(r.id),u=safeUrl(r.contactUrl);$('modalBody').innerHTML=`<div class="meta">${chip('',r.area)}${chip('',r.category)}${needs(r)}</div>${r.type==='event'?`<p><b>開催:</b> ${esc(r.dateStart)} 〜 ${esc(r.dateEnd)}</p>`:''}<div class="detail-copy">${esc(r.description)}</div>${extra}<div class="external-contact"><strong>連絡は外部で直接</strong><p>このサイトは連絡内容を中継・加工せず、契約成立にも関与しません。</p>${u?`<a class="btn primary" target="_blank" rel="noopener noreferrer" href="${esc(u)}">掲載者の公開窓口を開く</a>`:'<span class="muted">公開窓口なし</span>'}</div><div class="actions">${!self?'<button class="btn ghost" data-write-action id="reportBtn">問題を通報</button>':''}</div>${rec}`;$('modal').classList.add('open');bind($('modalBody'));if($('reportBtn'))$('reportBtn').onclick=()=>report(id);document.querySelectorAll('[data-write-action]').forEach(b=>b.disabled=!online)}
function closeModal(){$('modal').classList.remove('open')}
function toggleFav(id){const a=favs(),i=a.indexOf(id);i>=0?a.splice(i,1):a.push(id);setFav(a);renderAll()}
async function ready(){if(!online){toast('現在は書込みできません。');return false}if(!boot&&!(await bootstrap())){toast('管理鍵の初期化に失敗しました。');return false}return true}
async function report(id){if(!(await ready()))return;const reason=prompt('問題の内容を入力してください。','権利侵害・違法情報・虚偽情報等の確認依頼');if(reason===null||!txt(reason))return;try{await api('report',{method:'POST',auth:true,body:{listingId:id,reason:txt(reason)}});toast('通報を受け付けました。');await refresh();closeModal()}catch(e){toast(errmsg(e))}}
function mineCard(r){return`<article class="card"><div class="meta">${chip(r.type,T[r.type]||r.type)}${status(r)}</div><h3>${esc(r.title)}</h3><p>${esc((r.description||'').slice(0,130))}</p><div class="card-footer"><button class="btn primary small" data-edit="${r.id}">編集</button>${r.status==='stale'?`<button class="btn ghost small" data-renew="${r.id}">再公開</button>`:''}<button class="btn danger small" data-delete="${r.id}">削除</button></div></article>`}
function renderDashboard(){const mine=D.listings.filter(r=>r.status!=='deleted');$('mineGrid').innerHTML=mine.length?mine.map(mineCard).join(''):'<div class="empty">自分の掲載はありません。</div>';bind($('mineGrid'));const recs=[];for(const r of mine.filter(x=>x.status==='published')){if(r.type==='event')for(const x of recommendations(r).slice(0,6))recs.push({source:r,result:x});else for(const x of reverseRecommendations(r).slice(0,6))recs.push({source:r,result:x})}recs.sort((a,b)=>b.result.score-a.result.score);$('recommendationGrid').innerHTML=recs.length?recs.slice(0,20).map(x=>`<div class="recommend-wrap"><div class="muted small-label">「${esc(x.source.title)}」との候補</div>${card(x.result.r,x.result)}</div>`).join(''):'<div class="empty">条件一致候補はまだありません。</div>';bind($('recommendationGrid'));$('notificationList').innerHTML=D.notifications.length?D.notifications.map(n=>`<article class="notice-item ${n.status==='unread'?'unread':''}"><strong>${esc(n.title||'システム通知')}</strong><p>${esc(n.message||'')}</p><small>${esc((n.created_at||'').slice(0,10))}</small></article>`).join(''):'<div class="empty">通知はありません。</div>';$('identityBox').innerHTML=`管理ID: <code>${esc(identity().ownerId)}</code>　管理鍵はこの端末に保存されています。紛失時に復元できないためバックアップしてください。`;$('systemBox').innerHTML=`<h3>現在の運営範囲</h3><ul><li>有料販売：停止</li><li>非公開メッセージ：なし</li><li>雇用・求人求職・職業紹介・労働者派遣：禁止</li><li>会場予約・取引仲介：なし</li><li>利用者間決済・預かり：なし</li><li>おすすめ：公開済み客観条件のみ</li></ul><a href="legal-boundaries.html">取扱範囲の詳細</a>`}
function renderFav(){const a=favs().map(id=>R[id]).filter(Boolean);$('favGrid').innerHTML=a.length?a.map(r=>card(r)).join(''):'<div class="empty">お気に入りはありません。</div>';bind($('favGrid'))}
function renderAll(){renderBrowse();renderDashboard();renderFav()}
function formData(){return{id:txt($('editId').value)||undefined,type:postType,title:txt($('title').value),area:txt($('area').value),category:txt($('category').value),description:txt($('description').value),dateStart:$('dateStart').value,dateEnd:$('dateEnd').value,needs:[...document.querySelectorAll('.need:checked')].map(x=>x.value),availableFrom:$('availableFrom').value,availableTo:$('availableTo').value,capacity:+($('capacity').value||0),priceGuide:txt($('priceGuide').value),channels:txt($('channels').value),tags:txt($('tags').value).split(',').map(x=>x.trim()).filter(Boolean),contactUrl:txt($('contactUrl').value),venueInfoOnly:postType==='venue'&&$('venueInfoOnly').checked,contractorBusinessOnly:postType==='contractor'&&$('contractorBusinessOnly').checked}}
function localValidate(d){const e=[];if(d.title.length<4)e.push('タイトルは4文字以上必要です。');if(!d.area)e.push('地域を入力してください。');if(!d.category)e.push('カテゴリを選択してください。');if(d.description.length<20)e.push('説明は20文字以上必要です。');if(!safeUrl(d.contactUrl))e.push('公開用問い合わせURLはHTTPSで入力してください。');if(d.type==='event'&&(!d.dateStart||!d.dateEnd))e.push('イベントの開催期間を入力してください。');if(d.type==='venue'&&!d.venueInfoOnly)e.push('会場情報のみとして掲載する確認が必要です。');if(d.type==='contractor'&&!d.contractorBusinessOnly)e.push('業務委託サービスのみとして掲載する確認が必要です。');if(!$('terms').checked)e.push('利用規約等への同意が必要です。');return e}
async function submit(e){e.preventDefault();if(!(await ready()))return;const d=formData(),errs=localValidate(d);if(errs.length){$('validationBox').innerHTML=`<div class="validation error">${errs.map(x=>`<div>${esc(x)}</div>`).join('')}</div>`;return}const btn=$('submitBtn');btn.disabled=true;btn.textContent='確認中…';try{const out=await api('save_listing',{method:'POST',auth:true,body:d});$('validationBox').innerHTML=out.status==='review_required'?'<div class="validation warn">自動公開せず、確認待ちとして保存しました。</div>':'<div class="validation ok">公開しました。</div>';toast(out.status==='published'?'公開しました。':'確認待ちとして保存しました。');resetForm();await refresh();route('dashboard')}catch(err){const list=err.data?.errors||[];$('validationBox').innerHTML=`<div class="validation error">${(list.length?list:[errmsg(err)]).map(x=>`<div>${esc(x)}</div>`).join('')}</div>`}finally{btn.disabled=!online;btn.textContent='自動審査して掲載'}}
function edit(id){const r=D.listings.find(x=>x.id===id);if(!r)return;route('post');setType(r.type);$('editId').value=r.id;$('postHeading').textContent='掲載を編集';for(const [id2,val] of Object.entries({title:r.title,area:r.area,category:r.category,description:r.description,dateStart:r.dateStart,dateEnd:r.dateEnd,availableFrom:r.availableFrom,availableTo:r.availableTo,capacity:r.capacity||'',priceGuide:r.priceGuide,channels:r.channels,contactUrl:r.contactUrl}))if($(id2))$(id2).value=val;document.querySelectorAll('.need').forEach(x=>x.checked=(r.needs||[]).includes(x.value));$('tags').value=(r.tags||[]).join(', ');$('terms').checked=true;$('venueInfoOnly').checked=!!r.venueInfoOnly;$('contractorBusinessOnly').checked=!!r.contractorBusinessOnly}
async function del(id){if(!confirm('この掲載を削除しますか？'))return;if(!(await ready()))return;try{await api('delete_listing',{method:'POST',auth:true,body:{id}});toast('削除しました。');await refresh()}catch(e){toast(errmsg(e))}}
async function renew(id){if(!(await ready()))return;try{await api('renew_listing',{method:'POST',auth:true,body:{id}});toast('再公開しました。');await refresh()}catch(e){toast(errmsg(e))}}
function resetForm(){const f=$('postForm');f.reset();$('editId').value='';$('postHeading').textContent='掲載する';setType('event');$('validationBox').innerHTML=''}
function exportKey(){const data={app:'event-platform',version:2,identity:identity(),exportedAt:new Date().toISOString()};const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='event-platform-management-key.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function importKey(file){const reader=new FileReader();reader.onload=async()=>{try{const d=JSON.parse(reader.result);const v=d.identity;if(!v||!/^[0-9a-f-]{36}$/i.test(v.ownerId||'')||txt(v.ownerKey).length<32)throw new Error('invalid');if(!confirm('現在の管理鍵を置き換えます。続けますか？'))return;write('identity',v);boot=false;toast('管理鍵を復元しました。');await refresh()}catch{toast('有効な管理鍵ファイルではありません。')}};reader.readAsText(file)}
async function markRead(){if(!(await ready()))return;try{await api('mark_notifications_read',{method:'POST',auth:true,body:{}});await dashLoad();toast('既読にしました。')}catch(e){toast(errmsg(e))}}
async function health(){try{const d=await api('health');const safe=d.commercialPayments===false&&d.privateMessaging===false&&d.employmentMatching===false&&d.venueBrokerage===false&&d.underlyingPayments===false;toast(safe?`正常: ${d.build}`:'運営範囲の不整合を検出しました。')}catch{toast('APIに接続できません。')}}
function errmsg(e){const m={AUTH_REQUIRED:'管理鍵が必要です。',AUTH_FAILED:'管理鍵が一致しません。',MODERATION_REJECTED:'掲載条件を満たしていません。',DUPLICATE_REQUEST:'重複しています。',INTERNAL_ERROR:'サーバ処理に失敗しました。',UNKNOWN_ACTION:'この機能は提供していません。'};return m[e?.message]||'処理に失敗しました。'}
function wire(){document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',e=>{if(b.tagName==='A')return;e.preventDefault();route(b.dataset.nav)}));document.querySelectorAll('[data-post-type]').forEach(b=>b.onclick=()=>setType(b.dataset.postType));document.querySelectorAll('#q,#areaFilter').forEach(x=>x.addEventListener('input',renderBrowse));document.querySelectorAll('#typeFilter,#needFilter,#sort').forEach(x=>x.addEventListener('change',renderBrowse));$('postForm').addEventListener('submit',submit);$('resetBtn').onclick=resetForm;$('modalClose').onclick=closeModal;$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});$('exportBtn').onclick=exportKey;$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=e=>{if(e.target.files?.[0])importKey(e.target.files[0]);e.target.value=''};$('markReadBtn').onclick=markRead;$('healthBtn').onclick=health;document.querySelectorAll('[data-dash]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-dash]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.dash-panel').forEach(p=>p.classList.toggle('active',p.id===b.dataset.dash))})}
window.addEventListener('DOMContentLoaded',async()=>{wire();setType('event');const initial=['browse','post','dashboard','favorites'].includes(location.hash.slice(1))?location.hash.slice(1):'browse';route(initial);await refresh();console.info(`event-platform ${C.build}`)});
